name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      run: ./increment.ps1 -path "artifacts/packages"
    - name: Save artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: Nuget Packages
        path: artifacts/packages
